language: java

install:
  - "./gradlew wpi"
  - "./gradlew build"

script:
  - "./gradlew verify"

jdk:
  - oraclejdk8

notifications:
  email: false

cards:
  enabled:
    - "master"
  title: "Toast"