language: java
# Make NetworkTables happy
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6
      - junit4


before_install:
  - pip install --user codecov

install: ./gradlew build
script: ./gradlew $TEST_SUITE

# For CodeCov
after_success:
  - codecov
#  - bash <(curl -s https://codecov.io/bash)

jdk:
- oraclejdk8
notifications:
  email: false
  slack: 4828roboeagles:qjpsMMedvSTKBq3KCmDmdAjB
cards:
  enabled:
  - master
  - development
  title: Toast
env:
  - TEST_SUITE=test
  - TEST_SUITE=verify