codecov:
  branch: master

coverage:
  precision: 2
  round: down
  range: "70...100"

  notify:
    slack:
      default:
        url: "https://hooks.slack.com/services/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"
        threshold: 1%
        attachments: "sunburst, diff"
  status:
    project: yes
    patch: yes
    changes: yes

comment:
  layout: "header, diffu, changes, sunburst, ncovered, tree"
  behavior: default
